version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=lms
      - KEYCLOAK_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM_NAME=lms-realm
      - KEYCLOAK_CLIENT_ID=lms-client
      - KEYCLOAK_CLIENT_SECRET=secret-key
    depends_on:
      - mongo
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
